site_name: 小可 · 文档
site_url: https://bot.teahou.se/
site_author: Teahouse Studios

repo_url: https://github.com/Teahouse-Studios/bot
repo_name: Teahouse-Studios/bot

edit_uri: https://github.com/Teahouse-Studios/bot/edit/doc/docs/

nav:
  - 信息:
      - 首页: index.md
      - 常见问题: faq.md
      - 开始: setup.md
      - 权限: permission.md
  - 模块:
      - 简介: modules/index.md
      - 核心:
          - core: modules/core/core.md
          - ping: modules/core/ping.md
      - MediaWiki:
          - wiki: modules/wiki/wiki.md
          - interwiki: modules/wiki/interwiki.md
          - wiki_regex: modules/wiki/wiki_regex.md
          - wiki_infobox: modules/wiki/wiki_infobox.md
          - wiki_fandom_addon: modules/wiki/wiki_fandom_addon.md
          - wiki_gamepedia_addon: modules/wiki/wiki_gamepedia_addon.md
          - user: modules/wiki/user.md
      - GitHub:
          - github: modules/github.md
      - Mojira:
          - bug: modules/bug/bug.md
          - bug_regex: modules/bug/bug_regex.md
      - Minecraft 版本订阅:
          - mcv_rss: modules/mcv_rss/mcv_rss.md
          - mcv_jira_rss: modules/mcv_rss/mcv_jira_rss.md
      - Minecraft 实用工具:
          - server: modules/server.md
      - Minecraft Wiki 每周页面:
          - weekly: modules/weekly.md
      - Minecraft 版本更新:
          - mcv: modules/mcv/mcv.md
          - mcbv: modules/mcv/mcbv.md
          - mcdv: modules/mcv/mcdv.md
      - 音游分享工具:
          - b30（Arcaea）: modules/mug/b30.md
          - ptt（Arcaea）: modules/mug/ptt.md
          - cytoid: modules/mug/cytoid.md
      - MediaWiki 维护实用工具:
          - rc: modules/utils/rc.md
          - ab: modules/utils/ab.md
          - newbie: modules/utils/newbie.md

  - 开发:
      - 技术实现: dev/implementation.md
      - 新建模块指南: dev/new_module.md
      - infobox_render: dev/web_render.md

  - 条款和政策:
      - 隐私政策: policy/privacy.md

theme:
  name: material
  font:
  text: Source Sans Pro
  language: zh
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
  icon:
  repo: octicons/mark-github-16
  favicon: assets/favicon.ico
  logo: assets/logo.svg

extra:
  social:
    - icon: material/web
      link: https://teahou.se/
      name: Website
    - icon: octicons/mark-github-16
      link: https://github.com/Teahouse-Studios/
      name: GitHub
    - icon: material/email
      link: mailto:admin@teahou.se
      name: Email us

extra_css:
  - custom/custom.css

extra_javascript:
  - custom/custom.js

plugins:
  - search
  - minify

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - meta
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: Teahouse-Studios
      repo: bot
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

copyright: Copyright &copy; 2020-2021 Teahouse Studios
